name: "Comprobaciones básicas"
on: [pull_request]

jobs:
  check_pr:
    runs-on: ubuntu-latest
    steps:
    - name: ¿Tengo Perl?
      run:
        perl --version
    - name: Comprobaciones CC
      uses: JJ/github-pr-contains-action@releases/v2
      with:
        github-token: ${{github.token}}
        bodyContains: "] Prometo"
        bodyDoesNotContain: "orrar"
        filesChanged: 1
